#cloud-config
write_files:
 - path: /etc/server.conf
 owner: root:root
 permissions: "0644"
 content: |
 {
 "user": "${user}",
 "password": "${password}",
 "database": "${database}",
 "netloc": "${hostname}:${port}"
 }
 runcmd:
  -sudo apt-get update 
  -sudo apt-get install nginx
  